Refactor
sealcode/gpandoc pull request #1
Opened 2017-05-11 17:15 UTC by jaroslaw-wieczorek

2017-05-15 13:04 UTC, kuba-orlik requested changes
To na razie tyle z uwag czysto technicznych. Odnieś się do nich i możemy działać dalej :)

2017-05-15 13:04 UTC, kuba-orlik commented on settings.py
> +def isFolderExist(name):
To nie jest poprawne z gramatycznego punktu widzenia ;) Dodatkowo, "directory" (w skrócie: "dir" jest bardziej poprawne niż "folder". Opcje, jakie widzę to:

* `dirExists`,
* `doesDirExist`;

z silną preferencją co do opcji 1.

2017-05-15 13:04 UTC, kuba-orlik commented on settings.py
> +def crateFolderAboutName(name):
"About" w j. angielskim znaczy "o czymś", jak w "opowiadać o czymś". Nie można tego używać w znaczeniu "o nazwie" ;)

Proponuję: `createDir`

2017-05-15 13:04 UTC, kuba-orlik commented on settings.py
> +
Dodatkowo, te funkcje odnośnie sprawdzania istnienia i tworzenia katalogów nie mają sensu w module "settings". Lepiej utworzyć osobny moduł "util" i tam je wepchnąć - niech metody w module `settings` tyczą się samych ustawień.

2017-05-15 13:04 UTC, kuba-orlik commented on settings.py
> +from PyQt5.QtWidgets import QLabel
Już po importach widać, że mieszają się odpowiedzialności w tym pliku. 

Udało mi się zidentyfikować dwie odpowiedzialności tego modułu:

* zapis/odczyt ustawień do pliku
* gdzieniegdzie widzę zawołania do rzeczy Qtowych - więc ten moduł komunikuje się też w pewien sposób z widgetami.

Należy przepisać ten moduł tak, aby nie potrzebował Qt - wtedy łatwiejszym będzie np. pisanie wersji CLI gpandoca.

2017-05-15 13:04 UTC, kuba-orlik commented on settings_dialog.py
> +                      self, 'Uwaga', "Ustawienia zostaną wprowadzone \npo " +
Ałć. Dlaczego tak jest? Myślę, że lepiej będzie, jak zrobimy tak, aby nie trzeba było restartować aplikacji przy każdej zmianie ustawień...

2017-05-15 13:04 UTC, kuba-orlik commented on main_dialog.py
> +                "wszystkie (*);; " + "commonmark (*.commonmark);;" +
To można generować automatycznie, przy użyciu

```
# pandoc --list-input-formats
```

2017-05-16 05:53 UTC, ptasheq commented on settings.py
> +def isFolderExist(name):
Tak jak jest na pewno nie może zostać, ja akurat lubię dawać prefixy to funkcji zwracających boola. Z drugiej strony ```dirExists``` jest bardzo naturalne, też skłaniam się do tego.

2017-05-16 06:14 UTC, ptasheq commented on main_dialog.py
> +settings.sets = settings.loadConfiguration()
Nie podoba mi się ten double assignment - ukryte sprzężenie czasowe.

2017-05-16 07:46 UTC, jaroslaw-wieczorek commented on settings_dialog.py
> +                      self, 'Uwaga', "Ustawienia zostaną wprowadzone \npo " +
Próbowałem niestety nie wczytywały się zmiany do głównego okna. Na razie niech tak będzie.

2017-05-16 07:49 UTC, jaroslaw-wieczorek commented on main_dialog.py
> +                "wszystkie (*);; " + "commonmark (*.commonmark);;" +
Masz namyśli:
subprocess.run(['pandoc', '--list=input-formats'])?

2017-05-16 16:44 UTC, ptasheq requested changes
Więcej w chwili obecnej nie zauważyłem.

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +fixNameOfFile = QRegExp("(([\w\d])+([ ]||[-]||[_]))*")
Niejawne sprzężenie czasowe i double assignment, to by trzeba zmienić. Dodatkowo `fixNameOfFile `to dobra nazwa funkcji, ale zmiennej przechowywującej regexa niekoniecznie. Poza tym mam wątpliwości czy ten regex jest poprawny, alternatywę robi się pojedynczym `|`, nie powójnym.

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +        self.boxIsChecked = False
Raczej stosuje się taką konwencję `self.isBoxChecked`, chociaż to jest problematyczne może @kuba-orlik się wypowie, bo zachodzi tu sytuacja, że jest też funkcja co zwraca wartość tej zmiennej - `isBoxChecked()`, więc może zmienną nazwać `self.boxChecked`.

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +        if (self.list_widget_1.count()):
Dziwna konwencja, żeby w Pythonie wyrażenia w ifie brać w nawiasy - raczej jest to zbędne

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +        return self.isChecked
Po pierwsze czasem jest camelCase a czasem podkreślenia - brak spójności. Po drugie, można nazwać po prostu `isBoxChecked`, raczej return się nie stosuje w nazwie. Zauważ również, że to jest taki setterogetter bo funkcja nie tylko zwraca wartość, ale też uaktualnia polę klasy. Wydzieliłbym z funkcji drugą `updateBoxChecked`  i zmienił nazwę pola z `isChecked` na `boxChecked`, bo nie jest ona do końca szczęśliwa.

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +        return self.returnedFiles
J.w.

2017-05-16 16:44 UTC, ptasheq commented on main_dialog.py
> +                                          bookName)
To wywołanie metody jako argument brzydko wygląda. Utworzyłbym zmienne przed tym wywołaniem.

2017-05-16 16:44 UTC, ptasheq commented on recipe.py
>                                   (self.__class__.__name__, name))
A nie prościej:
```python
if name in ('list', 'string', 'text',):
  return [k for k, v in self['Variable'].items() if v == name]
elif name in ( 'image', 'outputFormat', 'template',):
  return [k for k, v in self['Document'].items() if v == name]
raise AttributeError(...)
```

2017-05-16 16:44 UTC, ptasheq commented on recipe_dialog.py
> +        return (self.loadedRecipe)
`getRecipe` i zbędny nawias.

2017-05-16 16:44 UTC, ptasheq commented on recipe_dialog.py
> +                self.label_2.setPixmap(pixmap)
Funkcja jest za długa proszę ją podzielić, chociażby wydzielić zawartość tego co jest w pętli.

2017-05-16 16:44 UTC, ptasheq commented on variables_dialog.py
> +    def get_values(self):
Proszę podzielić tę funkcję.

2017-05-16 16:44 UTC, ptasheq commented on variables_dialog.py
> +    def accept(self):
Tym bardziej proszę podzielić. Część kodu imho można wykorzystać wielokrotnie.

2017-07-02 15:16 UTC, jaroslaw-wieczorek commented on settings.py
> +from PyQt5.QtWidgets import QLabel
moduł ten potrzebuje Qt w jednym miejscu - przy zapisie typu fontowego do zmiennej.
    global font
    font = QFont(sets['user']['font-name'],
                 int(sets['user']['font-size']))
     
   dzięki temu font określa i typ rozmiar
CHYBA że:
globalną zmienną
font_size
font_name
i przy ustawianiu czcionki w widgecie skorzystać z rzutowania na QFont

2017-07-02 15:40 UTC, jaroslaw-wieczorek commented on settings.py
> +def isFolderExist(name):
done 👍

2017-07-02 15:41 UTC, jaroslaw-wieczorek commented on settings.py
> +def crateFolderAboutName(name):
Ok :)

2017-07-02 15:44 UTC, jaroslaw-wieczorek commented on settings.py
> +
done :)

2017-07-02 15:44 UTC, jaroslaw-wieczorek commented on settings_dialog.py
> +                      self, 'Uwaga', "Ustawienia zostaną wprowadzone \npo " +
w trakcie [***..]

2017-07-02 15:56 UTC, jaroslaw-wieczorek commented on main_dialog.py
> +        if (self.list_widget_1.count()):
oj sam się zdziwiłem ze to napisałem 👅

2017-07-08 17:58 UTC, jaroslaw-wieczorek commented on main_dialog.py
> +                "wszystkie (*);; " + "commonmark (*.commonmark);;" +
Uzupełnie ewentualne braki formatów - zadużo bawienia się z wywoływaniem pandoc --list-input-formats bo Qt sposób zapisu wygląda właśnie tak: 
"doc (*.doc);;"

2017-07-10 11:30 UTC, jaroslaw-wieczorek commented on recipe_dialog.py
> +        return (self.loadedRecipe)
done :)

2017-07-10 11:39 UTC, jaroslaw-wieczorek commented on main_dialog.py
> +fixNameOfFile = QRegExp("(([\w\d])+([ ]||[-]||[_]))*")
regex jest do poprawy sprzężenia czasowe usunięte

2017-11-05 20:09 UTC, merged